on:
 pull_request:
  types: [opened]
  
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: add assignees
        uses: actions-awsome/pr-helper@1.0.6
        with:
          actions: 'add-assignees, add-reviewers'
          token: ${{ github.token }}
          assignees: 'JeremyWuuuuu'
          pr-number: ${{ github.event.pull_request.number }}
