on:
 pull_request:
  types: [opened]
  
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-awsome/pr-helper
      - with:
        token: ${{ github.token }}
        assignees: 'jeremywu'
        pr-number: ${{ github.event.pull_request.number }}
